/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.38
 * Generated at: 2019-05-10 08:49:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.qna;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.text.SimpleDateFormat;
import java.util.Date;

public final class qna_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/C:/SSAFY1/last/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/SafeFood_Web_Vue_daejeon_3_kimdonguk_baeminsu/WEB-INF/lib/jstl-impl-1.2.jar!/META-INF/c.tld", Long.valueOf(1308094570000L));
    _jspx_dependants.put("jar:file:/C:/SSAFY1/last/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/SafeFood_Web_Vue_daejeon_3_kimdonguk_baeminsu/WEB-INF/lib/jstl-impl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1308094570000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-impl-1.2.jar", Long.valueOf(1557468536999L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.Date");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005frequestEncoding_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005ffmt_005frequestEncoding_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005ffmt_005frequestEncoding_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	request.setCharacterEncoding("utf-8");

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_fmt_005frequestEncoding_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html;charset=utf-8\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/main.css\" />\r\n");
      out.write("<noscript>\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"assets/css/noscript.css\" />\r\n");
      out.write("</noscript>\r\n");
      out.write("<title>SSAFY</title>\r\n");
      out.write("  <script src=\"https://unpkg.com/vue\"></script>\r\n");
      out.write("  <script src=\"https://cdnjs.cloudflare.com/ajax/libs/axios/0.18.0/axios.js\"></script>\r\n");
      out.write("  <script src=\"https://cdn.jsdelivr.net/npm/vue\"></script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/nav.jsp", out, false);
      out.write("\r\n");
      out.write("<div id='app'>\r\n");
      out.write("<div class='headtitle'><h2 v-html='currenttitle'></h2></div>\r\n");
      out.write("<div class='search_box'>\r\n");
      out.write("<a href='#' @click='showlist(1)'>게시판 추가</a> | \r\n");
      out.write("<a href='#' @click='showlist(0)'>모든게시물 보기</a>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<component v-bind:is = \"currentview\"></component>  \r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/x-template\" id=\"listhrmtemplate\">\r\n");
      out.write("<div>\r\n");
      out.write("<div>\r\n");
      out.write("<table class='list_table'>\r\n");
      out.write("<col width=\"10%\"><col width=\"20%\">\r\n");
      out.write("<col width=\"20%\"><col width=\"20%\"><col width=\"10%\"><col width=\"10%\">\r\n");
      out.write("<tr>\r\n");
      out.write("  <th>번호</th>\r\n");
      out.write("  <th>사용자</th>\r\n");
      out.write("  <th>제목</th>\r\n");
      out.write("  <th>날짜</th>\r\n");
      out.write("  <th>조회수</th>\r\n");
      out.write("   <th>비고</th>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr v-for=\"board in boards\" class = \"nicecolor\">\r\n");
      out.write("  <td v-html=\"board.number\"></td>\r\n");
      out.write("  <td v-html=\"board.user_id\"></td>\r\n");
      out.write("  <td v-html=\"board.title\" @click=\"show_detail(board.number)\"></td>\r\n");
      out.write("  <td v-html=\"board.date\"></td>\r\n");
      out.write("  <td v-html=\"board.click\"></td>\r\n");
      out.write("   <td class='button' @click=\"deleteboard(board.number)\"><input type=\"button\" class='blue' value='삭제'></button></td>\r\n");
      out.write("</tr>\r\n");
      out.write("</table>\r\n");
      out.write("</div>\r\n");
      out.write("<div>\r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/x-template\" id=\"addtemplate\">\r\n");
      out.write("<div>\r\n");
      out.write("   <div>\r\n");
      out.write("      <form action=\"\" method=\"post\" id=\"_frmForm\" name=\"frmForm\" @submit.prevent=\"addBoard\">\r\n");
      out.write("         <table class=\"content_table\">\r\n");
      out.write("            <colgroup>\r\n");
      out.write("                  <col style=\"width:30%;\" />\r\n");
      out.write("                  <col style=\"width:70%;\" />                     \r\n");
      out.write("            </colgroup>   \r\n");
      out.write("            <tr>\r\n");
      out.write("               <th>작성자</th>\r\n");
      out.write("               <td><input data-msg=\"작성자\" type=\"text\" name=\"user_id\" id=\"_name\" size=\"30\" v-model=\"cname\"/></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("               <th>제목</th>\r\n");
      out.write("               <td><input data-msg=\"제목\" type=\"text\" name=\"title\"  id=\"_title\" size=\"20\" v-model=\"ctitle\" /></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("               <th>내용</th>\r\n");
      out.write("               <td><input data-msg=\"내용\" type=\"text\" name=\"content\"  id=\"_content\" size=\"30\" v-model=\"ccontent\" /></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("               <th>작성일</th>\r\n");
      out.write("               <td><input data-msg=\"작성일\" type=\"date\" name=\"start_date\" id=\"_start_date\" size=\"30\" v-model=\"cstart_date\"/></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("               <td colspan=\"2\" style=\"height:50px; text-align:center;\">\r\n");
      out.write("               <button type=\"submit\" name=\"button\">게시판추가</button></td>\r\n");
      out.write("            </tr>         \r\n");
      out.write("         </table>\r\n");
      out.write("      </form>\r\n");
      out.write("   </div>\r\n");
      out.write("</div>\r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/x-template\" id=\"addanswertemplate\">\r\n");
      out.write("<div>\r\n");
      out.write("   <div>\r\n");
      out.write("      <form action=\"\" method=\"post\" id=\"_frmForm\" name=\"frmForm\" @submit.prevent=\"addAnswer\">\r\n");
      out.write("         <table class=\"content_table\">\r\n");
      out.write("            <colgroup>\r\n");
      out.write("                  <col style=\"width:30%;\" />\r\n");
      out.write("                  <col style=\"width:70%;\" />                     \r\n");
      out.write("            </colgroup>   \r\n");
      out.write("            <tr>\r\n");
      out.write("               <th>제목</th>\r\n");
      out.write("               <td><input data-msg=\"제목\" type=\"text\" name=\"title\"  id=\"_title\" size=\"20\" v-model=\"ctitle\" /></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("               <th>내용</th>\r\n");
      out.write("               <td><input data-msg=\"내용\" type=\"text\" name=\"content\"  id=\"_content\" size=\"30\" v-model=\"ccontent\" /></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("               <td colspan=\"2\" style=\"height:50px; text-align:center;\">\r\n");
      out.write("               <button type=\"submit\" name=\"button\">답변추가</button></td>\r\n");
      out.write("            </tr>         \r\n");
      out.write("         </table>\r\n");
      out.write("      </form>\r\n");
      out.write("   </div>\r\n");
      out.write("</div>\r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/x-template\" id=\"detailtemplate\">\r\n");
      out.write("<div>\r\n");
      out.write("   <table class='content_table'>\r\n");
      out.write("      <col width=\"10%\"><col width=\"20%\">\r\n");
      out.write("      <col width=\"20%\"><col width=\"20%\"><col width=\"10%\">\r\n");
      out.write("      <tr>\r\n");
      out.write("         <th>번호</th>\r\n");
      out.write("         <td v-html=\"board.number\"></td>\r\n");
      out.write("      </tr>\r\n");
      out.write("      <tr>\r\n");
      out.write("         <th>작성자</th>\r\n");
      out.write("         <td v-html=\"board.user_id\"></td>\r\n");
      out.write("      </tr>\r\n");
      out.write("      <tr>\r\n");
      out.write("         <th>제목</th>\r\n");
      out.write("         <td v-html=\"board.title\"></td>\r\n");
      out.write("      </tr>\r\n");
      out.write("      <tr>\r\n");
      out.write("         <th>내용</th>\r\n");
      out.write("         <td v-html=\"board.content\"></td>\r\n");
      out.write("      </tr>\r\n");
      out.write("      <tr>\r\n");
      out.write("         <th>작성일</th>\r\n");
      out.write("         <td v-html=\"board.date\"></td>\r\n");
      out.write("      </tr>\r\n");
      out.write("      <tr>\r\n");
      out.write("         <td class='button' @click=\"updateboard(board.number)\"><input type=\"button\" class='blue' value='수정'></button></td>\r\n");
      out.write("         <td class='button' @click=\"deleteboard(board.number)\"><input type=\"button\" class='blue' value='삭제'></button></td>\r\n");
      out.write("         <td class='button' @click=\"showlist(0)\"><input type=\"button\" class='blue' value='돌아가기'></button></td>\r\n");
      out.write("      </tr>\r\n");
      out.write("      <tr v-if=\"check === 'noshow'\">\r\n");
      out.write("         <td class='button' @click=\"addanswer(board.number)\"><input type=\"button\" class='blue' value='답글추가'></button></td>\r\n");
      out.write("      </tr>\r\n");
      out.write("   </table>\r\n");
      out.write("   <div v-if=\"check === 'show'\">\r\n");
      out.write("   <table class='content_table'>\r\n");
      out.write("      <tr>\r\n");
      out.write("         <th>제목</th>\r\n");
      out.write("         <td v-html=\"answer.title\"></td>\r\n");
      out.write("      </tr>\r\n");
      out.write("      <tr>\r\n");
      out.write("         <th>내용</th>\r\n");
      out.write("         <td v-html=\"answer.content\"></td>\r\n");
      out.write("      </tr>\r\n");
      out.write("      <tr>\r\n");
      out.write("         <th>작성일</th>\r\n");
      out.write("         <td v-html=\"answer.date\"></td>\r\n");
      out.write("      </tr>\r\n");
      out.write("      <tr>\r\n");
      out.write("         <td class='button' @click=\"updateanswer(answer.number)\"><input type=\"button\" class='blue' value='수정'></button></td>\r\n");
      out.write("      </tr>\r\n");
      out.write("      </table>\r\n");
      out.write("\r\n");
      out.write("   </div>\r\n");
      out.write("</div>\r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/x-template\" id=\"updateanswertemplate\">\r\n");
      out.write("<div>\r\n");
      out.write("   <div>\r\n");
      out.write("      <form action=\"\" method=\"post\" id=\"_frmForm\" name=\"frmForm\" @submit.prevent=\"updateAnswer\">\r\n");
      out.write("         <table class=\"content_table\">\r\n");
      out.write("            <colgroup>\r\n");
      out.write("                  <col style=\"width:30%;\" />\r\n");
      out.write("                  <col style=\"width:70%;\" />                     \r\n");
      out.write("            </colgroup>   \r\n");
      out.write("            <tr>\r\n");
      out.write("               <th>제목</th>\r\n");
      out.write("               <td><input id=\"_title\" v-model=\"ctitle\" type=\"text\" size=\"20\"/></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("               <th>내용</th>\r\n");
      out.write("               <td><input id=\"_content\" v-model=\"ccontent\" type=\"text\" size=\"30\"/></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("               <td colspan=\"2\" style=\"height:50px; text-align:center;\">\r\n");
      out.write("               <button type=\"submit\" name=\"button\">답변 수정</button></td>\r\n");
      out.write("            </tr>         \r\n");
      out.write("         </table>\r\n");
      out.write("      </form>\r\n");
      out.write("   </div>\r\n");
      out.write("</div>\r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/x-template\" id=\"updatetemplate\">\r\n");
      out.write("<div>\r\n");
      out.write("   <div>\r\n");
      out.write("      <form action=\"\" method=\"post\" id=\"_frmForm\" name=\"frmForm\" @submit.prevent=\"updateBoard\">\r\n");
      out.write("         <table class=\"content_table\">\r\n");
      out.write("            <colgroup>\r\n");
      out.write("                  <col style=\"width:30%;\" />\r\n");
      out.write("                  <col style=\"width:70%;\" />                     \r\n");
      out.write("            </colgroup>   \r\n");
      out.write("            <tr>\r\n");
      out.write("               <th>작성자</th>\r\n");
      out.write("               <td v-html=\"board.user_id\" v-model=\"cname\"></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("               <th>제목</th>\r\n");
      out.write("               <td><input id=\"_title\" type=\"text\" size=\"20\" v-model=\"ctitle\"/></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("               <th>내용</th>\r\n");
      out.write("               <td><input id=\"_content\" type=\"text\" size=\"30\" v-model=\"ccontent\"/></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("               <th>작성일</th>\r\n");
      out.write("               <td v-html=\"board.date\"></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("               <td colspan=\"2\" style=\"height:50px; text-align:center;\">\r\n");
      out.write("               <button type=\"submit\" name=\"button\">게시판 수정</button></td>\r\n");
      out.write("            </tr>         \r\n");
      out.write("         </table>\r\n");
      out.write("      </form>\r\n");
      out.write("   </div>\r\n");
      out.write("</div>\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("var addanswer = Vue.component('addanswer',{\r\n");
      out.write("   template: '#addanswertemplate',\r\n");
      out.write("   data(){\r\n");
      out.write("      return{\r\n");
      out.write("         boards: null,\r\n");
      out.write("         loading: true,\r\n");
      out.write("         errored: false,\r\n");
      out.write("         ctitle:'',\r\n");
      out.write("         ccontent:'',\r\n");
      out.write("         cstart_date:''\r\n");
      out.write("      }\r\n");
      out.write("   },\r\n");
      out.write("   methods:{\r\n");
      out.write("      addAnswer(){\r\n");
      out.write("         if(this.ctitle==''){alert('제목을 입력하세요.');return;}\r\n");
      out.write("         if(this.ccontent==''){alert('내용을 입력하세요.');return;}\r\n");
      out.write("         this.cstart_date=new Date();\r\n");
      out.write("            \r\n");
      out.write("         axios.post('http://localhost:8197/ssafyvue/api/addBoardAnswer/'+App.number,{\r\n");
      out.write("            title: this.ctitle,\r\n");
      out.write("            content: this.ccontent,\r\n");
      out.write("            date: this.cstart_date\r\n");
      out.write("         }).then(function(response){\r\n");
      out.write("            if(response.data.state=='succ'){\r\n");
      out.write("               alert(response.data.name+\"이 실행되었습니다.\");\r\n");
      out.write("               location.href='qna.do';\r\n");
      out.write("            }else{\r\n");
      out.write("               alert(response.data.name+\"에 실패하였습니다.\");\r\n");
      out.write("               location.href='qna.do';\r\n");
      out.write("            }\r\n");
      out.write("         });\r\n");
      out.write("      }}\r\n");
      out.write("   });\r\n");
      out.write("var detailboard = Vue.component('detailboard',{\r\n");
      out.write("   template: '#detailtemplate',\r\n");
      out.write("   data(){\r\n");
      out.write("      return{\r\n");
      out.write("         info: null,\r\n");
      out.write("         loading: true,\r\n");
      out.write("         errored: false,\r\n");
      out.write("         board:{},\r\n");
      out.write("         answer: {},\r\n");
      out.write("         check: \"show\"\r\n");
      out.write("      }\r\n");
      out.write("   },\r\n");
      out.write("   mounted(){\r\n");
      out.write("      axios\r\n");
      out.write("      .get('http://localhost:8197/ssafyvue/api/findBoardByNum/'+App.number)\r\n");
      out.write("      .then(response => (this.board = response.data))\r\n");
      out.write("      .catch(error =>{\r\n");
      out.write("         console.log(error)\r\n");
      out.write("         this.errored = true\r\n");
      out.write("      })\r\n");
      out.write("      .finally(() => this.loading = false);\r\n");
      out.write("      \r\n");
      out.write("      axios\r\n");
      out.write("      .get('http://localhost:8197/ssafyvue/api/findAnswerBoardByNum/'+App.number)\r\n");
      out.write("      .then(response => {\r\n");
      out.write("         this.answer = response.data\r\n");
      out.write("         console.log(this.answer);\r\n");
      out.write("         if(this.answer.title==null){\r\n");
      out.write("            this.check=\"noshow\";\r\n");
      out.write("         }\r\n");
      out.write("      })\r\n");
      out.write("      .catch(error=>{\r\n");
      out.write("         console.log(error)\r\n");
      out.write("         this.errored = true\r\n");
      out.write("      })\r\n");
      out.write("      .finally(() => this.loading = false);\r\n");
      out.write("      \r\n");
      out.write("\r\n");
      out.write("   },\r\n");
      out.write("   methods:{\r\n");
      out.write("      showlist:function(num){\r\n");
      out.write("         App.currentview='boardlist';\r\n");
      out.write("         App.showlist(0);\r\n");
      out.write("      },\r\n");
      out.write("      updateboard:function(num){\r\n");
      out.write("         App.number = num;\r\n");
      out.write("         App.currentview = 'updateboard';\r\n");
      out.write("         App.showlist(3);\r\n");
      out.write("      },\r\n");
      out.write("      deleteboard:function(num){\r\n");
      out.write("         App.number = num;\r\n");
      out.write("         axios\r\n");
      out.write("         .post('http://localhost:8197/ssafyvue/api/deleteBoard/'+App.number)\r\n");
      out.write("         .then(function(response){\r\n");
      out.write("            if(response.data.state=='succ'){\r\n");
      out.write("                 alert(response.data.name+\"이 실행되었습니다.\");\r\n");
      out.write("                 location.href='./qna.jsp';\r\n");
      out.write("              }else{\r\n");
      out.write("                 alert(response.data.name+\"이 실패하였습니다.\");\r\n");
      out.write("                 location.href='./qna.jsp';\r\n");
      out.write("              }\r\n");
      out.write("         })\r\n");
      out.write("         App.currentview = 'boardlist';\r\n");
      out.write("         App.showlist(0);\r\n");
      out.write("      },\r\n");
      out.write("      addanswer:function(num){\r\n");
      out.write("         App.number = num;\r\n");
      out.write("         App.currentview = 'addanswer';\r\n");
      out.write("         App.showlist(4);\r\n");
      out.write("      },\r\n");
      out.write("      updateanswer:function(num){\r\n");
      out.write("         App.number = num;\r\n");
      out.write("         App.currentview = 'updateanswer';\r\n");
      out.write("         App.showlist(5);\r\n");
      out.write("      }\r\n");
      out.write("   }\r\n");
      out.write("});\r\n");
      out.write("var boardlist = Vue.component('boardlist',{\r\n");
      out.write("    template: '#listhrmtemplate',\r\n");
      out.write("    data(){\r\n");
      out.write("        return {\r\n");
      out.write("          upHere : false,\r\n");
      out.write("          boards: [],\r\n");
      out.write("          loading: true,\r\n");
      out.write("          errored: false \r\n");
      out.write("        }\r\n");
      out.write("      },\r\n");
      out.write("      methods:{\r\n");
      out.write("       show_detail:function(number){\r\n");
      out.write("          alert(number+\"상세보기\");\r\n");
      out.write("          App.number = number;\r\n");
      out.write("          axios\r\n");
      out.write("          .get('http://localhost:8197/ssafyvue/api/updateBoardViewCnt/'+App.number)\r\n");
      out.write("          .then(function(response){\r\n");
      out.write("               if(response.data.state=='succ'){\r\n");
      out.write("               }else{\r\n");
      out.write("                  alert(response.data.name+\"이 실패하였습니다.\");\r\n");
      out.write("                  location.href='./qna.jsp';\r\n");
      out.write("               }\r\n");
      out.write("            })\r\n");
      out.write("            App.currentview = 'detailboard';\r\n");
      out.write("          App.showlist(2);\r\n");
      out.write("       },\r\n");
      out.write("          deleteboard:function(number){\r\n");
      out.write("            alert(number);\r\n");
      out.write("            App.number = number;\r\n");
      out.write("            axios\r\n");
      out.write("               .post('http://localhost:8197/ssafyvue/api/deleteBoard/'+App.number)\r\n");
      out.write("               .then(function(response){\r\n");
      out.write("                  if(response.data.state=='succ'){\r\n");
      out.write("                     alert(response.data.name+\"이 실행되었습니다.\");\r\n");
      out.write("                     location.href='./qna.jsp';\r\n");
      out.write("                  }else{\r\n");
      out.write("                     alert(response.data.name+\"이 실패하였습니다.\");\r\n");
      out.write("                     location.href='./qna.jsp';\r\n");
      out.write("                  }\r\n");
      out.write("               })\r\n");
      out.write("               .catch(error =>{\r\n");
      out.write("                  console.log(error)\r\n");
      out.write("                  this.errored = true\r\n");
      out.write("               })\r\n");
      out.write("               .finally(() => this.loading = false);\r\n");
      out.write("         } \r\n");
      out.write("      },\r\n");
      out.write("      mounted () {\r\n");
      out.write("        axios\r\n");
      out.write("          .get('http://localhost:8197/ssafyvue/api/findAllBoard')\r\n");
      out.write("          //.get('./emp.json')\r\n");
      out.write("          .then(response => (this.boards = response.data))\r\n");
      out.write("          .catch(error => {\r\n");
      out.write("            console.log(error)\r\n");
      out.write("            this.errored = true\r\n");
      out.write("          })\r\n");
      out.write("          .finally(() => this.loading = false);\r\n");
      out.write("      }\r\n");
      out.write("});\r\n");
      out.write("var addboard = Vue.component('addboard',{\r\n");
      out.write("   template: '#addtemplate',\r\n");
      out.write("   data(){\r\n");
      out.write("      return{\r\n");
      out.write("         boards: null,\r\n");
      out.write("         loading: true,\r\n");
      out.write("         errored: false,\r\n");
      out.write("         cname:'',\r\n");
      out.write("         ctitle:'',\r\n");
      out.write("         ccontent:'',\r\n");
      out.write("         cstart_date:''\r\n");
      out.write("      }\r\n");
      out.write("   },\r\n");
      out.write("   methods:{\r\n");
      out.write("      addBoard(){\r\n");
      out.write("         if(this.cname==''){alert('아이디를 입력하세요.'); return;}\r\n");
      out.write("         if(this.ctitle==''){alert('제목을 입력하세요.');return;}\r\n");
      out.write("         if(this.ccontent==''){alert('내용을 입력하세요.');return;}\r\n");
      out.write("         this.cstart_date=new Date();\r\n");
      out.write("            \r\n");
      out.write("         axios.post('http://localhost:8197/ssafyvue/api/addBoard',{\r\n");
      out.write("            user_id: this.cname,\r\n");
      out.write("            title: this.ctitle,\r\n");
      out.write("            content: this.ccontent,\r\n");
      out.write("            date: this.cstart_date\r\n");
      out.write("         }).then(function(response){\r\n");
      out.write("            if(response.data.state=='succ'){\r\n");
      out.write("               alert(response.data.name+\"이 실행되었습니다.\");\r\n");
      out.write("               location.href='./qna.jsp';\r\n");
      out.write("            }else{\r\n");
      out.write("               alert(response.data.name+\"에 실패하였습니다.\");\r\n");
      out.write("               location.href='./qna.jsp';\r\n");
      out.write("            }\r\n");
      out.write("         });\r\n");
      out.write("      }}\r\n");
      out.write("   });\r\n");
      out.write("var updateanswer = Vue.component('updateanswer',{\r\n");
      out.write("   template: '#updateanswertemplate',\r\n");
      out.write("   data(){\r\n");
      out.write("      return{\r\n");
      out.write("         loading: true,\r\n");
      out.write("         errored: false,\r\n");
      out.write("         answer:{},\r\n");
      out.write("         ctitle:'',\r\n");
      out.write("         ccontent:'',\r\n");
      out.write("         cstart_date:''\r\n");
      out.write("      }\r\n");
      out.write("   },\r\n");
      out.write("   mounted(){\r\n");
      out.write("      axios\r\n");
      out.write("      .get('http://localhost:8197/ssafyvue/api/findAnswerBoardByNum/'+App.number)\r\n");
      out.write("      .then(response => {\r\n");
      out.write("         this.answer = response.data\r\n");
      out.write("         this.ctitle = this.answer.title\r\n");
      out.write("         this.ccontent = this.answer.content\r\n");
      out.write("      })\r\n");
      out.write("      .catch(error =>{\r\n");
      out.write("         console.log(error)\r\n");
      out.write("         this.errored = true\r\n");
      out.write("      })\r\n");
      out.write("      .finally(() => this.loading = false);\r\n");
      out.write("   },\r\n");
      out.write("   methods:{\r\n");
      out.write("      updateAnswer:function(num){\r\n");
      out.write("         if(this.ctitle==''){alert('제목을 입력하세요.');return;}\r\n");
      out.write("         if(this.ccontent==''){alert('내용을 입력하세요.');return;}\r\n");
      out.write("         this.cstart_date=new Date();\r\n");
      out.write("         axios.post('http://localhost:8197/ssafyvue/api/updateBoardAnswer/'+App.number,{\r\n");
      out.write("            title: this.ctitle,\r\n");
      out.write("            content: this.ccontent,\r\n");
      out.write("            date: this.cstart_date\r\n");
      out.write("         }).then(function(response){\r\n");
      out.write("            if(response.data.state=='succ'){\r\n");
      out.write("               alert(response.data.name+\"이 실행되었습니다.\");\r\n");
      out.write("            }else{\r\n");
      out.write("               alert(response.data.name+\"에 실패하였습니다.\");\r\n");
      out.write("               location.href='./qna.jsp';\r\n");
      out.write("            }\r\n");
      out.write("            App.currentview = 'detailboard';\r\n");
      out.write("             App.showlist(2);\r\n");
      out.write("         });   \r\n");
      out.write("      }}\r\n");
      out.write("   });   \r\n");
      out.write("var updateboard = Vue.component('updateboard',{\r\n");
      out.write("   template: '#updatetemplate',\r\n");
      out.write("   data(){\r\n");
      out.write("      return{\r\n");
      out.write("         board: {},\r\n");
      out.write("         loading: true,\r\n");
      out.write("         errored: false,\r\n");
      out.write("         cnum: 0,\r\n");
      out.write("         cname:'',\r\n");
      out.write("         ctitle:'',\r\n");
      out.write("         ccontent:'',\r\n");
      out.write("         cstart_date:''\r\n");
      out.write("      }\r\n");
      out.write("   },\r\n");
      out.write("   mounted(){\r\n");
      out.write("       axios\r\n");
      out.write("         .get('http://localhost:8197/ssafyvue/api/findBoardByNum/'+App.number)\r\n");
      out.write("         .then(response => {this.board = response.data\r\n");
      out.write("               this.cnum = this.board.number\r\n");
      out.write("               this.ctitle = this.board.title\r\n");
      out.write("               this.ccontent = this.board.content\r\n");
      out.write("             })\r\n");
      out.write("         .catch(error => {\r\n");
      out.write("           console.log(error)\r\n");
      out.write("           this.errored = true\r\n");
      out.write("         })\r\n");
      out.write("         .finally(() => this.loading = false);\r\n");
      out.write("   },\r\n");
      out.write("   methods:{\r\n");
      out.write("      updateBoard:function(num){\r\n");
      out.write("         if(this.ctitle==''){alert('제목을 입력하세요.');return;}\r\n");
      out.write("         if(this.ccontent==''){alert('내용을 입력하세요.');return;}\r\n");
      out.write("         this.cstart_date=new Date();\r\n");
      out.write("         axios.post('http://localhost:8197/ssafyvue/api/updateBoard/'+App.number,{\r\n");
      out.write("            user_id: this.cname,\r\n");
      out.write("            title: this.ctitle,\r\n");
      out.write("            content: this.ccontent,\r\n");
      out.write("            date: this.cstart_date\r\n");
      out.write("         }).then(function(response){\r\n");
      out.write("            if(response.data.state=='succ'){\r\n");
      out.write("               alert(response.data.name+\"이 실행되었습니다.\");\r\n");
      out.write("            }else{\r\n");
      out.write("               alert(response.data.name+\"에 실패하였습니다.\");\r\n");
      out.write("               location.href='./qna.jsp';\r\n");
      out.write("            }\r\n");
      out.write("            App.currentview = 'detailboard';\r\n");
      out.write("             App.showlist(2);\r\n");
      out.write("         });\r\n");
      out.write("         \r\n");
      out.write("      }}\r\n");
      out.write("   });\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("var App=new Vue({\r\n");
      out.write("  el: '#app',\r\n");
      out.write("  data: {\r\n");
      out.write("     currenttitle:'SSAFY BOARD LIST',\r\n");
      out.write("     empid:'',\r\n");
      out.write("     currentview: 'boardlist',\r\n");
      out.write("      allviews:['boardlist','addboard','detailboard','updateboard','addanswer','updateanswer'],\r\n");
      out.write("      cutt:['SSAFY BOARD LIST','ADD BOARD','DETAILBOARD','UPDATE BOARD','ADD ANSWER','UPDATE ANSWER']\r\n");
      out.write("   },\r\n");
      out.write("   components: {\r\n");
      out.write("       boardlist: boardlist,\r\n");
      out.write("       addboard: addboard,\r\n");
      out.write("       detailboard: detailboard,\r\n");
      out.write("       addanswer: addanswer,\r\n");
      out.write("       updateanswer: updateanswer\r\n");
      out.write("     },\r\n");
      out.write("     methods:{\r\n");
      out.write("        showlist: function (val) {\r\n");
      out.write("           //alert(val);\r\n");
      out.write("          this.currentview=this.allviews[val];\r\n");
      out.write("           this.currenttitle=this.cutt[val];\r\n");
      out.write("           //listhrm\r\n");
      out.write("         }\r\n");
      out.write("     }\r\n");
      out.write("});\r\n");
      out.write("Vue.config.devtools = true;\r\n");
      out.write(" </script>\r\n");
      out.write(" \r\n");
      out.write(" ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/footer.jsp", out, false);
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_fmt_005frequestEncoding_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:requestEncoding
    org.apache.taglibs.standard.tag.rt.fmt.RequestEncodingTag _jspx_th_fmt_005frequestEncoding_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.RequestEncodingTag) _005fjspx_005ftagPool_005ffmt_005frequestEncoding_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.RequestEncodingTag.class);
    boolean _jspx_th_fmt_005frequestEncoding_005f0_reused = false;
    try {
      _jspx_th_fmt_005frequestEncoding_005f0.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005frequestEncoding_005f0.setParent(null);
      // /WEB-INF/views/qna/qna.jsp(10,0) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005frequestEncoding_005f0.setValue("utf-8");
      int _jspx_eval_fmt_005frequestEncoding_005f0 = _jspx_th_fmt_005frequestEncoding_005f0.doStartTag();
      if (_jspx_th_fmt_005frequestEncoding_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005frequestEncoding_0026_005fvalue_005fnobody.reuse(_jspx_th_fmt_005frequestEncoding_005f0);
      _jspx_th_fmt_005frequestEncoding_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005frequestEncoding_005f0, _jsp_getInstanceManager(), _jspx_th_fmt_005frequestEncoding_005f0_reused);
    }
    return false;
  }
}
